version: '2.21.0'

networks:
  spider:
    name: spider

services:
  planner:
    build:
      context: ./planner
      dockerfile: planner.dockerfile
    image: planner
    container_name: planner
    hostname: worker
    ports:
      - "3000:3000"
    networks:
      - spider

  worker1:
      build:
        context: ./worker
        dockerfile: worker.dockerfile
      image: worker
      container_name: worker1
      hostname: worker1
      ports:
        - "8080:8080"
      environment:
        - HOSTNAME=worker1
        - PORT=8080
      networks:
        - spider
      depends_on:
        - planner

  worker2:
      build:
        context: ./worker
        dockerfile: worker.dockerfile
      image: worker
      container_name: worker2
      hostname: worker2
      environment:
        - HOSTNAME=worker2
        - PORT=8070
      ports:
        - "8070:8070"
      networks:
        - spider
      depends_on:
        - planner       
